name: Desplegar terraform con mi web en la instancia y documentación de JS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      #  TERRAFORM DESTROY
      - name: Destroy Terraform
        run: |
          terraform destroy -auto-approve
