name: Desplegar o Destruir Terraform con mi web en la instancia y documentación de JS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Elige una opción'
        required: true
        type: choice
        options:
          - deploy
          - destroy
        default: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'deploy' }}

    steps:
      # CLONACIÓN DEL REPOSITORIO
      - name: Checkout repository
        uses: actions/checkout@v4

      # CREDENCIALES DE AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # INSTALAR PHP, PHPUNIT Y PHPDOCUMENTOR
      - name: Install PHP, PHPUnit, and phpDocumentor
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli php-mbstring unzip curl

          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

          composer global require phpunit/phpunit
          export PATH=$PATH:~/.composer/vendor/bin

          composer global require phpdocumentor/phpdocumentor
          export PATH=$PATH:~/.composer/vendor/bin

      # EJECUTAR PRUEBAS UNITARIAS CON PHPUNIT
      - name: Run PHPUnit Tests
        run: |
          cd proyTF/tests
          phpunit --bootstrap ../pagina/php/modelo/autoload.php UsuariosTest.php
          continue-on-error: false

      # GENERAR DOCUMENTACIÓN PHP
      - name: Generate PHP Documentation
        run: |
          phpDocumentor -d proyTF/pagina/php/modelo -t proyTF/pagina/php/docs

      # INSTALAR JSDOC
      - name: Install JSDoc
        run: |
          npm install -g jsdoc

      # DOCUMENTAR EL JAVASCRIPT
      - name: Generate Documentation
        run: |
          jsdoc ./pagina/ruleta.js -d ../docs

      # TERRAFORM INSTALL
      - name: Setup Terraform
        run: |
          cd tf
          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip
          unzip -o terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      # TERRAFORM INIT
      - name: TERRAFORM INIT
        run: |
          cd tf
          terraform init

      # TERRAFORM APPLY
      - name: TERRAFORM APPLY
        run: |
          cd tf
          terraform apply -auto-approve

      # SUBIR .tfstate A S3
      - name: Upload Terraform State to S3
        run: |
          aws s3 cp tf/terraform.tfstate s3://nmr_bucket/terraform.tfstate
          
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}

    steps:
      # CLONACIÓN DEL REPOSITORIO
      - name: Checkout repository
        uses: actions/checkout@v4

      # CREDENCIALES DE AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # INSTALAR TERRAFORM
      - name: Setup Terraform
        run: |
          cd tf
          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.4.0/terraform_1.4.0_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      # DESCARGAR EL .tfstate DESDE S3
      - name: Download Terraform State from S3
        run: |
          aws s3 cp s3://nmr_bucket/terraform.tfstate .

      # TERRAFORM DESTROY
      - name: TERRAFORM DESTROY
        run: |
          cd tf
          terraform destroy -auto-approve

      # DESTRUIR EL ARCHIVO .tfstate DE S3
      - name: Delete Terraform State from S3
        run: |
          aws s3 rm s3://nmr_bucket/terraform.tfstate
